package ch.epfl.blchatel.leveleditor.io;

/**
 * Brushes Resources "Table of Contents"
 * If we want to add brushes:
 *   1. Add the Backgrounds, Foregrounds and Behaviors Images into the resources folder
 *   2. Use ComputeBrushesRes program to compute this enum content
 *   3. Replace the current content by the computed one
 *   4. Build LevelEditor again
 */
public enum BrushesRes {

    // Do not edit before
    //////////////////////////////////////////////////////////////////////////////

    // Please Copy the following output to the enum BrushesRes
    // ...

    DIRT_1("dirt.1.png"),
    DIRT_BORDER_1("dirt.border.1.png"),
    DIRT_BORDER_10("dirt.border.10.png"),
    DIRT_BORDER_11("dirt.border.11.png"),
    DIRT_BORDER_12("dirt.border.12.png"),
    DIRT_BORDER_2("dirt.border.2.png"),
    DIRT_BORDER_3("dirt.border.3.png"),
    DIRT_BORDER_4("dirt.border.4.png"),
    DIRT_BORDER_5("dirt.border.5.png"),
    DIRT_BORDER_6("dirt.border.6.png"),
    DIRT_BORDER_7("dirt.border.7.png"),
    DIRT_BORDER_8("dirt.border.8.png"),
    DIRT_BORDER_9("dirt.border.9.png"),
    DOOR_CLOSE_1("door.close.1.png"),
    DOOR_CLOSE_2("door.close.2.png"),
    DOOR_OPEN_1("door.open.1.png"),
    DOOR_OPEN_2("door.open.2.png"),
    DOOR_OPEN_3("door.open.3.png"),
    DOOR_OPEN_4("door.open.4.png"),
    FENCE_1("fence.1.png"),
    FENCE_2("fence.2.png"),
    FENCE_3("fence.3.png"),
    FENCE_4("fence.4.png"),
    FENCE_5("fence.5.png"),
    FENCE_6("fence.6.png"),
    FLOOR_1("floor.1.png"),
    FLOOR_2("floor.2.png"),
    FLOOR_3("floor.3.png"),
    FLOOR_4("floor.4.png"),
    FLOOR_5("floor.5.png"),
    FLOOR_6("floor.6.png"),
    FLOOR_7("floor.7.png"),
    FLOOR_CARPET_BORDER_1("floor.carpet.border.1.png"),
    FLOOR_CARPET_BORDER_2("floor.carpet.border.2.png"),
    FLOOR_CARPET_BORDER_3("floor.carpet.border.3.png"),
    FLOOR_CARPET_BORDER_4("floor.carpet.border.4.png"),
    FLOOR_CARPET_BORDER_5("floor.carpet.border.5.png"),
    FLOOR_CARPET_BORDER_6("floor.carpet.border.6.png"),
    FLOOR_CARPET_BORDER_7("floor.carpet.border.7.png"),
    FLOOR_CARPET_BORDER_8("floor.carpet.border.8.png"),
    FLOOR_CARPET("floor.carpet.png"),
    GRASS_1("grass.1.png"),
    GRASS_2("grass.2.png"),
    GRASS_3("grass.3.png"),
    GRASS_BORDER_1("grass.border.1.png"),
    GRASS_BORDER_10("grass.border.10.png"),
    GRASS_BORDER_11("grass.border.11.png"),
    GRASS_BORDER_12("grass.border.12.png"),
    GRASS_BORDER_13("grass.border.13.png"),
    GRASS_BORDER_14("grass.border.14.png"),
    GRASS_BORDER_2("grass.border.2.png"),
    GRASS_BORDER_3("grass.border.3.png"),
    GRASS_BORDER_4("grass.border.4.png"),
    GRASS_BORDER_5("grass.border.5.png"),
    GRASS_BORDER_6("grass.border.6.png"),
    GRASS_BORDER_7("grass.border.7.png"),
    GRASS_BORDER_8("grass.border.8.png"),
    GRASS_BORDER_9("grass.border.9.png"),
    OBJECT_BARIL_1("object.baril.1.png"),
    OBJECT_BARIL_2("object.baril.2.png"),
    OBJECT_BARIL_3("object.baril.3.png"),
    OBJECT_BARIL_4("object.baril.4.png"),
    OBJECT_BARIL_5("object.baril.5.png"),
    OBJECT_BARIL_6("object.baril.6.png"),
    OBJECT_BOX_1("object.box.1.png"),
    OBJECT_BOX_2("object.box.2.png"),
    ROOF_BROWN_FLAT_1("roof.brown.flat.1.png"),
    ROOF_BROWN_FLAT_2("roof.brown.flat.2.png"),
    ROOF_BROWN_FLAT_3("roof.brown.flat.3.png"),
    ROOF_BROWN_FLAT_4("roof.brown.flat.4.png"),
    ROOF_BROWN_FLAT_5("roof.brown.flat.5.png"),
    ROOF_BROWN_FLAT_6("roof.brown.flat.6.png"),
    ROOF_BROWN_HIGH_1("roof.brown.high.1.png"),
    ROOF_BROWN_HIGH_2("roof.brown.high.2.png"),
    ROOF_BROWN_HIGH_3("roof.brown.high.3.png"),
    ROOF_BROWN_HIGH_4("roof.brown.high.4.png"),
    ROOF_BROWN_HIGH_5("roof.brown.high.5.png"),
    ROOF_BROWN_HIGH_6("roof.brown.high.6.png"),
    ROOF_BROWN_MEDIUM_1("roof.brown.medium.1.png"),
    ROOF_BROWN_MEDIUM_2("roof.brown.medium.2.png"),
    ROOF_BROWN_MEDIUM_3("roof.brown.medium.3.png"),
    ROOF_BROWN_MEDIUM_4("roof.brown.medium.4.png"),
    ROOF_BROWN_MEDIUM_5("roof.brown.medium.5.png"),
    ROOF_BROWN_MEDIUM_6("roof.brown.medium.6.png"),
    ROOF_BROWN_OTHER_1("roof.brown.other.1.png"),
    ROOF_BROWN_OTHER_2("roof.brown.other.2.png"),
    ROOF_BROWN_OTHER_3("roof.brown.other.3.png"),
    ROOF_GRAY_FLAT_1("roof.gray.flat.1.png"),
    ROOF_GRAY_FLAT_2("roof.gray.flat.2.png"),
    ROOF_GRAY_FLAT_3("roof.gray.flat.3.png"),
    ROOF_GRAY_FLAT_4("roof.gray.flat.4.png"),
    ROOF_GRAY_FLAT_5("roof.gray.flat.5.png"),
    ROOF_GRAY_FLAT_6("roof.gray.flat.6.png"),
    ROOF_GRAY_HIGH_1("roof.gray.high.1.png"),
    ROOF_GRAY_HIGH_2("roof.gray.high.2.png"),
    ROOF_GRAY_HIGH_3("roof.gray.high.3.png"),
    ROOF_GRAY_HIGH_4("roof.gray.high.4.png"),
    ROOF_GRAY_HIGH_5("roof.gray.high.5.png"),
    ROOF_GRAY_HIGH_6("roof.gray.high.6.png"),
    ROOF_GRAY_MEDIUM_1("roof.gray.medium.1.png"),
    ROOF_GRAY_MEDIUM_2("roof.gray.medium.2.png"),
    ROOF_GRAY_MEDIUM_3("roof.gray.medium.3.png"),
    ROOF_GRAY_MEDIUM_4("roof.gray.medium.4.png"),
    ROOF_GRAY_MEDIUM_5("roof.gray.medium.5.png"),
    ROOF_GRAY_MEDIUM_6("roof.gray.medium.6.png"),
    ROOF_GRAY_OTHER_1("roof.gray.other.1.png"),
    ROOF_GRAY_OTHER_2("roof.gray.other.2.png"),
    ROOF_GRAY_OTHER_3("roof.gray.other.3.png"),
    STAIRES_GRAY_1("staires.gray.1.png"),
    STAIRES_GRAY_2("staires.gray.2.png"),
    STAIRES_GRAY_3("staires.gray.3.png"),
    STAIRES_GRAY_4("staires.gray.4.png"),
    STAIRES_GRAY_5("staires.gray.5.png"),
    STAIRES_GRAY_6("staires.gray.6.png"),
    STAIRES_WHITE_1("staires.white.1.png"),
    STAIRES_WHITE_2("staires.white.2.png"),
    STAIRES_WHITE_3("staires.white.3.png"),
    STAIRES_WHITE_4("staires.white.4.png"),
    STAIRES_WHITE_5("staires.white.5.png"),
    STAIRES_WHITE_6("staires.white.6.png"),
    TREE_GORANGE_BIGTOP("tree.gorange.bigTop.png"),
    TREE_GREEN1_BIGBOTTOM("tree.green1.bigBottom.png"),
    TREE_GREEN1_BIGTOP("tree.green1.bigTop.png"),
    TREE_GREEN1_HUGEBOTTOM("tree.green1.hugeBottom.png"),
    TREE_GREEN1_HUGETOP("tree.green1.hugeTop.png"),
    TREE_GREEN1_MEDIUM("tree.green1.medium.png"),
    TREE_GREEN1_SMALL("tree.green1.small.png"),
    TREE_GREEN2_BIGBOTTOM("tree.green2.bigBottom.png"),
    TREE_GREEN2_BIGTOP("tree.green2.bigTop.png"),
    TREE_GREEN2_HUGEBOTTOM("tree.green2.hugeBottom.png"),
    TREE_GREEN2_HUGETOP("tree.green2.hugeTop.png"),
    TREE_GREEN2_MEDIUM("tree.green2.medium.png"),
    TREE_GREEN2_SMALL("tree.green2.small.png"),
    TREE_ORANGE_BIGBOTTOM("tree.orange.bigBottom.png"),
    TREE_ORANGE_HUGEBOTTOM("tree.orange.hugeBottom.png"),
    TREE_ORANGE_HUGETOP("tree.orange.hugeTop.png"),
    TREE_ORANGE_MEDIUM("tree.orange.medium.png"),
    TREE_ORANGE_SMALL("tree.orange.small.png"),
    WALL_GRAY_1("wall.gray.1.png"),
    WALL_GRAY_10("wall.gray.10.png"),
    WALL_GRAY_11("wall.gray.11.png"),
    WALL_GRAY_12("wall.gray.12.png"),
    WALL_GRAY_13("wall.gray.13.png"),
    WALL_GRAY_14("wall.gray.14.png"),
    WALL_GRAY_15("wall.gray.15.png"),
    WALL_GRAY_16("wall.gray.16.png"),
    WALL_GRAY_17("wall.gray.17.png"),
    WALL_GRAY_18("wall.gray.18.png"),
    WALL_GRAY_19("wall.gray.19.png"),
    WALL_GRAY_2("wall.gray.2.png"),
    WALL_GRAY_20("wall.gray.20.png"),
    WALL_GRAY_21("wall.gray.21.png"),
    WALL_GRAY_22("wall.gray.22.png"),
    WALL_GRAY_23("wall.gray.23.png"),
    WALL_GRAY_24("wall.gray.24.png"),
    WALL_GRAY_25("wall.gray.25.png"),
    WALL_GRAY_26("wall.gray.26.png"),
    WALL_GRAY_27("wall.gray.27.png"),
    WALL_GRAY_28("wall.gray.28.png"),
    WALL_GRAY_29("wall.gray.29.png"),
    WALL_GRAY_3("wall.gray.3.png"),
    WALL_GRAY_30("wall.gray.30.png"),
    WALL_GRAY_31("wall.gray.31.png"),
    WALL_GRAY_32("wall.gray.32.png"),
    WALL_GRAY_33("wall.gray.33.png"),
    WALL_GRAY_34("wall.gray.34.png"),
    WALL_GRAY_35("wall.gray.35.png"),
    WALL_GRAY_36("wall.gray.36.png"),
    WALL_GRAY_37("wall.gray.37.png"),
    WALL_GRAY_38("wall.gray.38.png"),
    WALL_GRAY_39("wall.gray.39.png"),
    WALL_GRAY_4("wall.gray.4.png"),
    WALL_GRAY_40("wall.gray.40.png"),
    WALL_GRAY_41("wall.gray.41.png"),
    WALL_GRAY_5("wall.gray.5.png"),
    WALL_GRAY_6("wall.gray.6.png"),
    WALL_GRAY_7("wall.gray.7.png"),
    WALL_GRAY_8("wall.gray.8.png"),
    WALL_GRAY_9("wall.gray.9.png"),
    WALL_WHITE_1("wall.white.1.png"),
    WALL_WHITE_10("wall.white.10.png"),
    WALL_WHITE_11("wall.white.11.png"),
    WALL_WHITE_12("wall.white.12.png"),
    WALL_WHITE_13("wall.white.13.png"),
    WALL_WHITE_14("wall.white.14.png"),
    WALL_WHITE_15("wall.white.15.png"),
    WALL_WHITE_16("wall.white.16.png"),
    WALL_WHITE_17("wall.white.17.png"),
    WALL_WHITE_18("wall.white.18.png"),
    WALL_WHITE_19("wall.white.19.png"),
    WALL_WHITE_2("wall.white.2.png"),
    WALL_WHITE_20("wall.white.20.png"),
    WALL_WHITE_21("wall.white.21.png"),
    WALL_WHITE_22("wall.white.22.png"),
    WALL_WHITE_23("wall.white.23.png"),
    WALL_WHITE_24("wall.white.24.png"),
    WALL_WHITE_25("wall.white.25.png"),
    WALL_WHITE_26("wall.white.26.png"),
    WALL_WHITE_27("wall.white.27.png"),
    WALL_WHITE_28("wall.white.28.png"),
    WALL_WHITE_3("wall.white.3.png"),
    WALL_WHITE_4("wall.white.4.png"),
    WALL_WHITE_5("wall.white.5.png"),
    WALL_WHITE_6("wall.white.6.png"),
    WALL_WHITE_7("wall.white.7.png"),
    WALL_WHITE_8("wall.white.8.png"),
    WALL_WHITE_9("wall.white.9.png"),
    WATER_1("water.1.png"),
    WATER_BORDER_1("water.border.1.png"),
    WATER_BORDER_10("water.border.10.png"),
    WATER_BORDER_11("water.border.11.png"),
    WATER_BORDER_12("water.border.12.png"),
    WATER_BORDER_2("water.border.2.png"),
    WATER_BORDER_3("water.border.3.png"),
    WATER_BORDER_4("water.border.4.png"),
    WATER_BORDER_5("water.border.5.png"),
    WATER_BORDER_6("water.border.6.png"),
    WATER_BORDER_7("water.border.7.png"),
    WATER_BORDER_8("water.border.8.png"),
    WATER_BORDER_9("water.border.9.png"),
    WINDOW_CLOSE_1("window.close.1.png"),
    WINDOW_CLOSE_10("window.close.10.png"),
    WINDOW_CLOSE_11("window.close.11.png"),
    WINDOW_CLOSE_12("window.close.12.png"),
    WINDOW_CLOSE_13("window.close.13.png"),
    WINDOW_CLOSE_14("window.close.14.png"),
    WINDOW_CLOSE_15("window.close.15.png"),
    WINDOW_CLOSE_16("window.close.16.png"),
    WINDOW_CLOSE_2("window.close.2.png"),
    WINDOW_CLOSE_3("window.close.3.png"),
    WINDOW_CLOSE_4("window.close.4.png"),
    WINDOW_CLOSE_5("window.close.5.png"),
    WINDOW_CLOSE_6("window.close.6.png"),
    WINDOW_CLOSE_7("window.close.7.png"),
    WINDOW_CLOSE_8("window.close.8.png"),
    WINDOW_CLOSE_9("window.close.9.png"),
    WINDOW_OPEN_1("window.open.1.png"),
    WINDOW_OPEN_10("window.open.10.png"),
    WINDOW_OPEN_11("window.open.11.png"),
    WINDOW_OPEN_12("window.open.12.png"),
    WINDOW_OPEN_13("window.open.13.png"),
    WINDOW_OPEN_14("window.open.14.png"),
    WINDOW_OPEN_15("window.open.15.png"),
    WINDOW_OPEN_16("window.open.16.png"),
    WINDOW_OPEN_2("window.open.2.png"),
    WINDOW_OPEN_3("window.open.3.png"),
    WINDOW_OPEN_4("window.open.4.png"),
    WINDOW_OPEN_5("window.open.5.png"),
    WINDOW_OPEN_6("window.open.6.png"),
    WINDOW_OPEN_7("window.open.7.png"),
    WINDOW_OPEN_8("window.open.8.png"),
    WINDOW_OPEN_9("window.open.9.png");

    //////////////////////////////////////////////////////////////////////////////
    // Do not edit after

    private final static String BRUSHES_BACKGROUND_PATH = "Brushes/Backgrounds/";
    private final static String BRUSHES_FOREGROUND_PATH = "Brushes/Foregrounds/";
    private final static String BRUSHES_BEHAVIOR_PATH = "Brushes/Behaviors/";

    public final String name, background, foreground, behavior;

    BrushesRes(String name){
        this.name = name;
        this.background = BRUSHES_BACKGROUND_PATH + name;
        this.foreground = BRUSHES_FOREGROUND_PATH + name;
        this.behavior = BRUSHES_BEHAVIOR_PATH + name;
    }
}
